### ISSUE TITLE
编译时突然内存使用率飙高

### ISSUE THREAD

**Issue by y7could** [oceanengine/ad_open_sdk_go#3]

**Comment by houseme** [comment]
有优化的计划吗？

**Comment by y7could** [comment]
得看巨量这边，目前只能直接用他们的接口直接对接，不再使用这个sdk

**Comment by houseme** [comment]
> 得看巨量这边，目前只能直接用他们的接口直接对接，不再使用这个sdk

这个sdk 全是API接口直接生成的代码，代码质量太差了，2核4G的机器编译负载直接就宕机了。

**Comment by y7could** [comment]
该sdk无法使用了的，，直接对接接口好点，都怕线上出故障，而且提Issues被直接关了，听说有群反馈这个问题，巨量都不理会

**Comment by houseme** [comment]
> 该sdk无法使用了的，，直接对接接口好点，都怕线上出故障，而且提Issues被直接关了，听说有群反馈这个问题，巨量都不理会

那就是“拿绩效”的作品呗。

**Comment by houseme** [comment]
> 该sdk无法使用了的，，直接对接接口好点，都怕线上出故障，而且提Issues被直接关了，听说有群反馈这个问题，巨量都不理会

一些朋友 推荐使用 https://github.com/bububa/oceanengine
