### ISSUE TITLE
获取星广联投视频数据返回字段不全

### ISSUE THREAD

**Issue by toshiNie** [oceanengine/ad_open_sdk_go#7]
文档: https://open.oceanengine.com/labels/34/docs/1795147063924819
response: models/model_report_stardelivery_task_video_data_get_v3_0_response_data_list_inner.go

**Comment by onionwyl** [comment]
<img width="646" alt="image" src="https://github.com/user-attachments/assets/7823511d-7957-41da-91ff-a0cc6f645d91">
这个接口的字段生成暂时有些问题，可以先用Execute返回的httpRes手动解析一下json，我们会尽快修复。

**Comment by onionwyl** [comment]
已修复

**Comment by OceanengineOpenApi** [comment]
fixed
